config: reschedule forks for unit test network
New forks schedule is needed to be able to properly generate/restore basic chain
once Notary will be included in Echidna fork.

This commit also fixes a bug of statesync.Module when it's impossible to
initialize module after state sync is completed because of missing
MaxTraceableBlocks storage item if reffering by temporary storage
prefix:
```
    --- FAIL: TestStateSyncModule_Init/initialization_from_headers/blocks/mpt_synced_stages (0.01s)
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	initial gas supply is not set or wrong, setting default value	{"InitialGASSupply": "52000000"}
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	Genesis MaxTraceableBlocks is not set or wrong, using default value	{"Genesis MaxTraceableBlocks": 3}
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	Genesis MaxValidUntilBlockIncrement is not set or wrong, using default value	{"Genesis MaxValidUntilBlockIncrement": 5760}
        logger.go:146: 2025-04-30T12:55:43.567+0300	INFO	GarbageCollectionPeriod is not set or wrong, using default value	{"GarbageCollectionPeriod": 10000}
        logger.go:146: 2025-04-30T12:55:43.569+0300	INFO	no storage version found! creating genesis block
        logger.go:146: 2025-04-30T12:55:43.570+0300	INFO	try to sync state for the latest state synchronisation point	{"point": 8, "evaluated chain's blockHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.570+0300	DEBUG	done processing headers	{"headerIndex": 1, "blockHeight": 0, "took": "458.95µs"}
        logger.go:146: 2025-04-30T12:55:43.570+0300	DEBUG	done processing headers	{"headerIndex": 2, "blockHeight": 0, "took": "438.832µs"}
        logger.go:146: 2025-04-30T12:55:43.571+0300	DEBUG	done processing headers	{"headerIndex": 3, "blockHeight": 0, "took": "430.826µs"}
        logger.go:146: 2025-04-30T12:55:43.571+0300	DEBUG	done processing headers	{"headerIndex": 4, "blockHeight": 0, "took": "455.433µs"}
        logger.go:146: 2025-04-30T12:55:43.572+0300	DEBUG	done processing headers	{"headerIndex": 5, "blockHeight": 0, "took": "266.015µs"}
        logger.go:146: 2025-04-30T12:55:43.572+0300	DEBUG	done processing headers	{"headerIndex": 6, "blockHeight": 0, "took": "266.615µs"}
        logger.go:146: 2025-04-30T12:55:43.572+0300	DEBUG	done processing headers	{"headerIndex": 7, "blockHeight": 0, "took": "409.386µs"}
        logger.go:146: 2025-04-30T12:55:43.573+0300	DEBUG	done processing headers	{"headerIndex": 8, "blockHeight": 0, "took": "397.653µs"}
        logger.go:146: 2025-04-30T12:55:43.573+0300	DEBUG	done processing headers	{"headerIndex": 9, "blockHeight": 0, "took": "390.179µs"}
        logger.go:146: 2025-04-30T12:55:43.573+0300	INFO	headers are in sync	{"headerHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.573+0300	INFO	MPT billet initialized	{"height": 8, "state root": "c3d0e2d2905577864b43abdf995bd9c95084036983020b7c80b26786f35341fc"}
        logger.go:146: 2025-04-30T12:55:43.573+0300	INFO	try to sync state for the latest state synchronisation point	{"point": 8, "evaluated chain's blockHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.573+0300	INFO	headers are in sync	{"headerHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.573+0300	INFO	MPT billet initialized	{"height": 8, "state root": "c3d0e2d2905577864b43abdf995bd9c95084036983020b7c80b26786f35341fc"}
        logger.go:146: 2025-04-30T12:55:43.574+0300	INFO	try to sync state for the latest state synchronisation point	{"point": 8, "evaluated chain's blockHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.574+0300	INFO	headers are in sync	{"headerHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.574+0300	INFO	MPT billet initialized	{"height": 8, "state root": "c3d0e2d2905577864b43abdf995bd9c95084036983020b7c80b26786f35341fc"}
        logger.go:146: 2025-04-30T12:55:43.576+0300	INFO	MPT is in sync	{"height": 8}
        logger.go:146: 2025-04-30T12:55:43.576+0300	INFO	try to sync state for the latest state synchronisation point	{"point": 8, "evaluated chain's blockHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.576+0300	INFO	headers are in sync	{"headerHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.576+0300	INFO	MPT billet initialized	{"height": 8, "state root": "c3d0e2d2905577864b43abdf995bd9c95084036983020b7c80b26786f35341fc"}
        logger.go:146: 2025-04-30T12:55:43.577+0300	INFO	MPT is in sync	{"stateroot height": 8}
        logger.go:146: 2025-04-30T12:55:43.577+0300	INFO	blocks are in sync	{"blockHeight": 8}
        logger.go:146: 2025-04-30T12:55:43.577+0300	INFO	state is in sync	{"state sync point": 8}
        logger.go:146: 2025-04-30T12:55:43.577+0300	INFO	jumping to state sync point	{"state sync point": 8}
        logger.go:146: 2025-04-30T12:55:43.577+0300	INFO	try to sync state for the latest state synchronisation point	{"point": 8, "evaluated chain's blockHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.577+0300	INFO	headers are in sync	{"headerHeight": 9}
        logger.go:146: 2025-04-30T12:55:43.577+0300	INFO	MPT billet initialized	{"height": 8, "state root": "c3d0e2d2905577864b43abdf995bd9c95084036983020b7c80b26786f35341fc"}
        logger.go:146: 2025-04-30T12:55:43.578+0300	INFO	MPT is in sync	{"stateroot height": 8}
        logger.go:146: 2025-04-30T12:55:43.578+0300	INFO	persisted to disk	{"blocks": 0, "keys": 225, "headerHeight": 9, "blockHeight": 8, "took": "54.213µs"}
    logger.go:146: 2025-04-30T12:55:43.578+0300	INFO	persisted to disk	{"blocks": 9, "keys": 278, "headerHeight": 9, "blockHeight": 9, "took": "79.611µs"}
panic: failed to retrieve MaxTraceableBlock storage item from Policy contract storage by key 70f9ffffff17 at height 8: key not found [recovered]
	panic: failed to retrieve MaxTraceableBlock storage item from Policy contract storage by key 70f9ffffff17 at height 8: key not found

goroutine 195 [running]:
testing.tRunner.func1.2({0xdce600, 0xc0000ad3c0})
	/home/anna/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/home/anna/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1635 +0x35e
panic({0xdce600?, 0xc0000ad3c0?})
	/home/anna/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/panic.go:785 +0x132
github.com/nspcc-dev/neo-go/pkg/core/statesync.(*Module).getLatestSavedBlock(0xc0001ec8c0, 0x8)
	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/core/statesync/module.go:314 +0x437
github.com/nspcc-dev/neo-go/pkg/core/statesync.(*Module).defineSyncStage(0xc0001ec8c0)
	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/core/statesync/module.go:279 +0x9fe
github.com/nspcc-dev/neo-go/pkg/core/statesync.(*Module).Init(0xc0001ec8c0, 0x9)
	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/core/statesync/module.go:190 +0x465
github.com/nspcc-dev/neo-go/pkg/core/statesync_test.TestStateSyncModule_Init.func9(0xc00018e340)
	/home/anna/Documents/GitProjects/nspcc-dev/neo-go/pkg/core/statesync/neotest_test.go:237 +0x1265
testing.tRunner(0xc00018e340, 0xc00028bc68)
	/home/anna/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 64
	/home/anna/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1743 +0x390

```

Signed-off-by: Anna Shaleva <shaleva.ann@nspcc.ru>